# Generated by Django 2.2.3 on 2021-02-08 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cog',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Name of the cog')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Name of the command')),
                ('cog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Cog', verbose_name='Cog this command belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='DBGuild',
            fields=[
                ('g_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Discord ID of the server')),
                ('name', models.CharField(max_length=256, verbose_name='Discord name of the server')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of adding the guild')),
                ('prefix', models.CharField(default='!', max_length=512, verbose_name='Prefix for guild')),
            ],
        ),
        migrations.CreateModel(
            name='DBRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=None, null=True, verbose_name='Position on the board')),
                ('role_id', models.BigIntegerField(verbose_name='Discord ID of the role')),
                ('role_name', models.CharField(default=None, max_length=512, null=True, verbose_name='Role name')),
                ('role_color_r', models.BigIntegerField(default=None, null=True, verbose_name='Red part of role color')),
                ('role_color_g', models.BigIntegerField(default=None, null=True, verbose_name='Green part of the role color')),
                ('role_color_b', models.BigIntegerField(default=None, null=True, verbose_name='Blue part of the role color')),
                ('base_role', models.BooleanField(default=False, verbose_name='Base role for the server')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DBGuild', verbose_name='Associated server')),
            ],
            options={
                'unique_together': {('g', 'role_id')},
            },
        ),
        migrations.CreateModel(
            name='DBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.BigIntegerField(verbose_name='Discord id of the user')),
                ('u_name', models.CharField(default='', max_length=64, verbose_name='Discord display name of the user')),
                ('avatar_url', models.URLField(default=None, null=True, verbose_name='Avatar url of the account')),
                ('is_bot', models.BooleanField(default=False)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DBGuild', verbose_name='Associated server')),
            ],
            options={
                'unique_together': {('u_id', 'g')},
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp this happened')),
                ('total_count', models.BigIntegerField(verbose_name='Total count of users that are stored in the bot')),
                ('u', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.DBUser', verbose_name='User that was added to the bot')),
            ],
        ),
        migrations.CreateModel(
            name='GuildStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp this happened')),
                ('count', models.BigIntegerField(verbose_name='Count up or downward')),
                ('total_count', models.BigIntegerField(verbose_name='Total count of guilds the bot is on')),
                ('g_joined', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guildstats_guild_join', to='db.DBGuild', verbose_name='Guild that joined the server to their community')),
                ('g_left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guildstats_guild_leave', to='db.DBGuild', verbose_name='Guild that removed the bot from their server')),
                ('related_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.GuildStats', verbose_name='Related object (i.e. when they joined it)')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_string', models.CharField(max_length=2048, verbose_name='Command string that was executed')),
                ('error_type', models.CharField(max_length=256, verbose_name='Error type')),
                ('error', models.CharField(max_length=5000, verbose_name='Error string')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of error.')),
                ('traceback', models.CharField(default=None, max_length=15000, null=True, verbose_name='Traceback of error')),
                ('g', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.DBGuild', verbose_name='Guild where error happened')),
            ],
        ),
        migrations.CreateModel(
            name='CommandStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(default=None, max_length=2048, null=True, verbose_name='Parameters of the command')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp this command was executed')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Command', verbose_name='Command that was executed')),
                ('g', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.DBGuild', verbose_name='Guild that used the command')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.DBUser', verbose_name='User that executed this command')),
            ],
        ),
        migrations.CreateModel(
            name='ModRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DBGuild', verbose_name='Guild associated to this mod')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DBRole', verbose_name='Role that makes user mods')),
            ],
            options={
                'unique_together': {('g', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DBChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(verbose_name='Discord ID of the channel')),
                ('channel_name', models.CharField(default=None, max_length=524, null=True, verbose_name='Discord name of the channel')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DBGuild', verbose_name='Associated server')),
            ],
            options={
                'unique_together': {('g', 'channel_id')},
            },
        ),
    ]
