# Generated by Django 2.2.3 on 2021-02-11 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.BigIntegerField(verbose_name='Discord id of the user')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount of money that was betted')),
                ('team', models.CharField(default=None, max_length=100, verbose_name='Team name')),
                ('profit', models.IntegerField(default=0, verbose_name='Amount of profit/loss recieved')),
                ('odds', models.CharField(default=None, max_length=10, verbose_name='Odds for the bet')),
                ('code', models.CharField(default=None, max_length=5, verbose_name='League code of bet')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('u_id', 'amount', 'team', 'profit', 'odds', 'timestamp', 'code')},
            },
        ),
    ]
